// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type ChatReply struct {
	ThreadID string  `json:"threadId"`
	Message  string  `json:"message"`
	Phone    *string `json:"phone,omitempty"`
}

type CreateProductInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	PriceCents  int    `json:"priceCents"`
}

type CreateStoreInput struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Category    string  `json:"category"`
	City        string  `json:"city"`
	Phone       *string `json:"phone,omitempty"`
	Address     *string `json:"address,omitempty"`
}

type HomePayload struct {
	City             string             `json:"city"`
	RankedStores     []*RankedStore     `json:"rankedStores"`
	TrendingProducts []*TrendingProduct `json:"trendingProducts"`
	TrendingReviews  []*TrendingReview  `json:"trendingReviews"`
}

type Mutation struct {
}

type Photo struct {
	ID        string `json:"id"`
	URL       string `json:"url"`
	SortOrder int    `json:"sortOrder"`
}

type Product struct {
	ID             string    `json:"id"`
	Slug           string    `json:"slug"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	PriceCents     int       `json:"priceCents"`
	DisplayPrice   string    `json:"displayPrice"`
	Store          *Store    `json:"store"`
	Photos         []*Photo  `json:"photos"`
	Reviews        []*Review `json:"reviews"`
	UpvoteCount    int       `json:"upvoteCount"`
	ViewerHasVoted bool      `json:"viewerHasVoted"`
	CreatedAt      time.Time `json:"createdAt"`
}

type Query struct {
}

type RankedStore struct {
	Store          *Store  `json:"store"`
	Rank           int     `json:"rank"`
	CommunityScore float64 `json:"communityScore"`
	FeedScore      float64 `json:"feedScore"`
}

type Review struct {
	ID              string    `json:"id"`
	Rating          int       `json:"rating"`
	Body            string    `json:"body"`
	AuthorFirstName string    `json:"authorFirstName"`
	Store           *Store    `json:"store,omitempty"`
	Product         *Product  `json:"product,omitempty"`
	CreatedAt       time.Time `json:"createdAt"`
}

type SearchResult struct {
	Stores   []*Store   `json:"stores"`
	Products []*Product `json:"products"`
}

type Store struct {
	ID             string     `json:"id"`
	Slug           string     `json:"slug"`
	Name           string     `json:"name"`
	Description    string     `json:"description"`
	Category       string     `json:"category"`
	City           string     `json:"city"`
	Phone          *string    `json:"phone,omitempty"`
	Address        *string    `json:"address,omitempty"`
	Photos         []*Photo   `json:"photos"`
	Products       []*Product `json:"products"`
	Reviews        []*Review  `json:"reviews"`
	UpvoteCount    int        `json:"upvoteCount"`
	CommunityScore float64    `json:"communityScore"`
	ViewerHasVoted bool       `json:"viewerHasVoted"`
	CreatedAt      time.Time  `json:"createdAt"`
}

type TrendingProduct struct {
	Product *Product `json:"product"`
	Heat    float64  `json:"heat"`
}

type TrendingReview struct {
	Review *Review `json:"review"`
	Heat   float64 `json:"heat"`
}

type UpdateProductInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	PriceCents  *int    `json:"priceCents,omitempty"`
}

type UpdateStoreInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Category    *string `json:"category,omitempty"`
	City        *string `json:"city,omitempty"`
	Phone       *string `json:"phone,omitempty"`
	Address     *string `json:"address,omitempty"`
}

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
	Name  string `json:"name"`
	Role  Role   `json:"role"`
}

type AffinityEventKind string

const (
	AffinityEventKindViewCategory AffinityEventKind = "VIEW_CATEGORY"
	AffinityEventKindViewStore    AffinityEventKind = "VIEW_STORE"
	AffinityEventKindViewProduct  AffinityEventKind = "VIEW_PRODUCT"
	AffinityEventKindSearch       AffinityEventKind = "SEARCH"
	AffinityEventKindVote         AffinityEventKind = "VOTE"
	AffinityEventKindReview       AffinityEventKind = "REVIEW"
)

var AllAffinityEventKind = []AffinityEventKind{
	AffinityEventKindViewCategory,
	AffinityEventKindViewStore,
	AffinityEventKindViewProduct,
	AffinityEventKindSearch,
	AffinityEventKindVote,
	AffinityEventKindReview,
}

func (e AffinityEventKind) IsValid() bool {
	switch e {
	case AffinityEventKindViewCategory, AffinityEventKindViewStore, AffinityEventKindViewProduct, AffinityEventKindSearch, AffinityEventKindVote, AffinityEventKindReview:
		return true
	}
	return false
}

func (e AffinityEventKind) String() string {
	return string(e)
}

func (e *AffinityEventKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AffinityEventKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AffinityEventKind", str)
	}
	return nil
}

func (e AffinityEventKind) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AffinityEventKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AffinityEventKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleCustomer Role = "CUSTOMER"
	RoleOwner    Role = "OWNER"
	RoleAdmin    Role = "ADMIN"
)

var AllRole = []Role{
	RoleCustomer,
	RoleOwner,
	RoleAdmin,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleCustomer, RoleOwner, RoleAdmin:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TimeWindow string

const (
	TimeWindowToday TimeWindow = "TODAY"
	TimeWindowWeek  TimeWindow = "WEEK"
	TimeWindowAll   TimeWindow = "ALL"
)

var AllTimeWindow = []TimeWindow{
	TimeWindowToday,
	TimeWindowWeek,
	TimeWindowAll,
}

func (e TimeWindow) IsValid() bool {
	switch e {
	case TimeWindowToday, TimeWindowWeek, TimeWindowAll:
		return true
	}
	return false
}

func (e TimeWindow) String() string {
	return string(e)
}

func (e *TimeWindow) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TimeWindow(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TimeWindow", str)
	}
	return nil
}

func (e TimeWindow) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TimeWindow) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TimeWindow) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
