package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"bytes"
	"context"
	"encoding/base64"
	"strings"

	"github.com/google/uuid"
	"github.com/rajat/localdiscovery/internal/adapter/blob"
	"github.com/rajat/localdiscovery/internal/adapter/graphql/generated"
	"github.com/rajat/localdiscovery/internal/adapter/graphql/model"
	"github.com/rajat/localdiscovery/internal/domain"
	"github.com/rajat/localdiscovery/internal/usecase"
)

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, email string, password string, name string, role *model.Role) (*model.User, error) {
	rl := domain.RoleCustomer
	if role != nil {
		rl = domain.ParseRole(string(*role))
	}
	sess, err := r.Auth.Signup(ctx, email, password, name, rl, GuestFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	SetSessionCookie(ctx, sess.Token)
	return mapUser(sess.User), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.User, error) {
	sess, err := r.Auth.Login(ctx, email, password, GuestFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	SetSessionCookie(ctx, sess.Token)
	return mapUser(sess.User), nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	ClearSessionCookie(ctx)
	return true, nil
}

// BecomeOwner is the resolver for the becomeOwner field.
func (r *mutationResolver) BecomeOwner(ctx context.Context) (*model.User, error) {
	sess, err := r.Auth.BecomeOwner(ctx, PrincipalFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	SetSessionCookie(ctx, sess.Token)
	return mapUser(sess.User), nil
}

// RecordAffinityEvent is the resolver for the recordAffinityEvent field.
func (r *mutationResolver) RecordAffinityEvent(ctx context.Context, category string, kind model.AffinityEventKind) (bool, error) {
	err := r.Affinity.Record(ctx, PrincipalFrom(ctx), GuestFrom(ctx), category, domain.AffinityKind(kind))
	if err != nil {
		return false, gqlErr(err)
	}
	return true, nil
}

// Vote is the resolver for the vote field.
func (r *mutationResolver) Vote(ctx context.Context, storeID *string, productID *string) (bool, error) {
	voted, err := r.Votes.Vote(ctx, PrincipalFrom(ctx), storeID, productID)
	if err != nil {
		return false, gqlErr(err)
	}
	return voted, nil
}

// CreateReview is the resolver for the createReview field.
func (r *mutationResolver) CreateReview(ctx context.Context, storeID *string, productID *string, rating int, body string) (*model.Review, error) {
	rv, err := r.Reviews.Create(ctx, PrincipalFrom(ctx), storeID, productID, rating, body)
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapReview(rv), nil
}

// CreateStore is the resolver for the createStore field.
func (r *mutationResolver) CreateStore(ctx context.Context, input model.CreateStoreInput) (*model.Store, error) {
	st, err := r.Listing.CreateStore(ctx, PrincipalFrom(ctx), usecase.StoreInput{
		Name: input.Name, Description: input.Description, Category: input.Category, City: input.City,
		Phone: input.Phone, Address: input.Address,
	})
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapStoreLite(st, nil), nil
}

// UpdateStore is the resolver for the updateStore field.
func (r *mutationResolver) UpdateStore(ctx context.Context, id string, input model.UpdateStoreInput) (*model.Store, error) {
	in := usecase.StoreInput{
		Name: deref(input.Name), Description: deref(input.Description),
		Category: deref(input.Category), City: deref(input.City),
		Phone: input.Phone, Address: input.Address,
	}
	st, err := r.Listing.UpdateStore(ctx, PrincipalFrom(ctx), id, in)
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapStoreLite(st, nil), nil
}

// DeleteStore is the resolver for the deleteStore field.
func (r *mutationResolver) DeleteStore(ctx context.Context, id string) (bool, error) {
	if err := r.Listing.DeleteStore(ctx, PrincipalFrom(ctx), id); err != nil {
		return false, gqlErr(err)
	}
	return true, nil
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, storeID string, input model.CreateProductInput) (*model.Product, error) {
	p, err := r.Listing.CreateProduct(ctx, PrincipalFrom(ctx), storeID, usecase.ProductInput{
		Name: input.Name, Description: input.Description, PriceCents: input.PriceCents,
	})
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapProduct(p, nil, nil, nil, 0, false), nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, input model.UpdateProductInput) (*model.Product, error) {
	in := usecase.ProductInput{PriceCents: -1}
	if input.Name != nil {
		in.Name = *input.Name
	}
	if input.Description != nil {
		in.Description = *input.Description
	}
	if input.PriceCents != nil {
		in.PriceCents = *input.PriceCents
	}
	p, err := r.Listing.UpdateProduct(ctx, PrincipalFrom(ctx), id, in)
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapProduct(p, nil, nil, nil, 0, false), nil
}

// UploadPhoto is the resolver for the uploadPhoto field.
func (r *mutationResolver) UploadPhoto(ctx context.Context, storeID *string, productID *string, filename string, contentBase64 string) (*model.Photo, error) {
	raw := contentBase64
	if i := strings.Index(raw, ","); i >= 0 {
		raw = raw[i+1:]
	}
	b, err := base64.StdEncoding.DecodeString(raw)
	if err != nil {
		return nil, domain.ErrInvalid
	}
	key := blob.KeyFor(uuid.NewString(), filename)
	url, err := r.Blob.Put(ctx, key, bytes.NewReader(b), "")
	if err != nil {
		return nil, err
	}
	ph, err := r.Listing.AddPhoto(ctx, PrincipalFrom(ctx), storeID, productID, url)
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapPhoto(ph), nil
}

// Chat is the resolver for the chat field.
func (r *mutationResolver) Chat(ctx context.Context, storeID *string, productID *string, threadID *string, message string) (*model.ChatReply, error) {
	reply, err := r.Chats.Chat(ctx, deref(storeID), deref(productID), deref(threadID), message)
	if err != nil {
		return nil, gqlErr(err)
	}
	return &model.ChatReply{ThreadID: reply.ThreadID, Message: reply.Message, Phone: reply.Phone}, nil
}

// Home is the resolver for the home field.
func (r *queryResolver) Home(ctx context.Context, city *string, category *string, window *model.TimeWindow) (*model.HomePayload, error) {
	w := "ALL"
	if window != nil {
		w = string(*window)
	}
	page, err := r.Homes.Home(ctx, deref(city), deref(category), w, PrincipalFrom(ctx), GuestFrom(ctx), nil)
	if err != nil {
		return nil, gqlErr(err)
	}
	storeIDs := make([]string, 0, len(page.RankedStores)+len(page.TrendingProducts))
	prodIDs := make([]string, 0, len(page.TrendingProducts))
	for _, rs := range page.RankedStores {
		storeIDs = append(storeIDs, rs.Store.ID)
	}
	for _, tp := range page.TrendingProducts {
		storeIDs = append(storeIDs, tp.Store.ID)
		prodIDs = append(prodIDs, tp.Product.ID)
	}
	sPhotos, _ := r.Listing.PhotosForStores(ctx, storeIDs)
	pPhotos, _ := r.Listing.PhotosForProducts(ctx, prodIDs)

	ranked := make([]*model.RankedStore, 0, len(page.RankedStores))
	for _, rs := range page.RankedStores {
		ranked = append(ranked, &model.RankedStore{
			Store:          mapStore(rs.Store, sPhotos[rs.Store.ID], nil, nil, rs.Upvotes, false, rs.CommunityScore),
			Rank:           rs.Rank,
			CommunityScore: rs.CommunityScore,
			FeedScore:      rs.FeedScore,
		})
	}
	tprods := make([]*model.TrendingProduct, 0, len(page.TrendingProducts))
	for _, tp := range page.TrendingProducts {
		st := mapStoreLite(tp.Store, sPhotos[tp.Store.ID])
		tprods = append(tprods, &model.TrendingProduct{
			Product: mapProduct(tp.Product, st, pPhotos[tp.Product.ID], nil, 0, false),
			Heat:    tp.Heat,
		})
	}
	trevs := make([]*model.TrendingReview, 0, len(page.TrendingReviews))
	for _, tr := range page.TrendingReviews {
		trevs = append(trevs, &model.TrendingReview{Review: mapReview(tr.Review), Heat: tr.Heat})
	}
	return &model.HomePayload{
		City:             page.City,
		RankedStores:     ranked,
		TrendingProducts: tprods,
		TrendingReviews:  trevs,
	}, nil
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, q string, city *string) (*model.SearchResult, error) {
	res, err := r.Searcher.Search(ctx, q, deref(city))
	if err != nil {
		return nil, gqlErr(err)
	}
	sIDs := make([]string, len(res.Stores))
	for i, s := range res.Stores {
		sIDs[i] = s.ID
	}
	pIDs := make([]string, len(res.Products))
	for i, p := range res.Products {
		pIDs[i] = p.ID
	}
	sPhotos, _ := r.Listing.PhotosForStores(ctx, sIDs)
	pPhotos, _ := r.Listing.PhotosForProducts(ctx, pIDs)
	stores := make([]*model.Store, 0, len(res.Stores))
	for _, s := range res.Stores {
		stores = append(stores, mapStoreLite(s, sPhotos[s.ID]))
	}
	products := make([]*model.Product, 0, len(res.Products))
	for _, p := range res.Products {
		products = append(products, mapProduct(p, nil, pPhotos[p.ID], nil, 0, false))
	}
	return &model.SearchResult{Stores: stores, Products: products}, nil
}

// Store is the resolver for the store field.
func (r *queryResolver) Store(ctx context.Context, slug string) (*model.Store, error) {
	d, err := r.Listing.StoreBySlug(ctx, slug, PrincipalFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapStoreDetail(d), nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, slug string) (*model.Product, error) {
	d, err := r.Listing.ProductBySlug(ctx, slug, PrincipalFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapProductDetail(d), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	p := PrincipalFrom(ctx)
	if p == nil {
		return nil, nil
	}
	u, err := r.Auth.Me(ctx, p)
	if err != nil {
		return nil, nil
	}
	return mapUser(u), nil
}

// MyStores is the resolver for the myStores field.
func (r *queryResolver) MyStores(ctx context.Context) ([]*model.Store, error) {
	stores, err := r.Listing.OwnerStores(ctx, PrincipalFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	ids := make([]string, len(stores))
	for i, s := range stores {
		ids[i] = s.ID
	}
	photos, _ := r.Listing.PhotosForStores(ctx, ids)
	out := make([]*model.Store, 0, len(stores))
	for _, s := range stores {
		out = append(out, mapStoreLite(s, photos[s.ID]))
	}
	return out, nil
}

// OidcLabel is the resolver for the oidcLabel field.
func (r *queryResolver) OidcLabel(ctx context.Context) (string, error) {
	if r.OIDCLabel == "" {
		return "Continue with OpenID", nil
	}
	return r.OIDCLabel, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
